apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: patroni-stat
spec:
  serviceName: patroni
  replicas: 3
  selector:
    matchLabels:
      app: patroni-stat
  template:
    metadata:
      labels:
        app: patroni-stat
    spec:
      serviceAccountName: patroni-sa
      containers:
      - name: patroni
        image: teta42/patroni
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SLEEPNESS
          value: "2" # Кол-во секунд между проверками
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 5432
        - containerPort: 8008
  volumeClaimTemplates:
  - metadata:
      name: data-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi