apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
  selector:
    app: etcd-stat

---

apiVersion: v1
kind: Service
metadata:
  name: patroni-primary
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: patroni-api
      port: 8008
      targetPort: 8008
  selector:
    app: patroni-stat
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: patroni-replica
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: patroni-api
      port: 8008
      targetPort: 8008
  selector:
    app: patroni-stat
    role: replica
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort