apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patroni-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "update", "verbs"]