apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd-stat
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app: etcd-stat
  template:
    metadata:
      labels:
        app: etcd-stat
    spec:
      containers:
      - name: etcd
        image: bitnami/etcd
        env:
        - name: ETCD_DATA_DIR
          value: /etcd-data
        - name: ETCD_LISTEN_CLIENT_URLS
          value: http://0.0.0.0:2379
        - name: ETCD_ADVERTISE_CLIENT_URLS
          value: http://etcd:2379
        - name: ALLOW_NONE_AUTHENTICATION
          value: "yes"
        - name: ETCD_ENABLE_V2
          value: "true"
        ports:
        - containerPort: 2379
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi


--- # Сервис


apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
    - port: 2379
      targetPort: 2379
      protocol: TCP
  selector:
    app: etcd-stat