apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patroni-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: patroni-sa
  namespace: default
roleRef:
  kind: Role
  name: patroni-role
  apiGroup: rbac.authorization.k8s.io